### ISSUE TITLE
Traceback (most recent call last):                  File "/storage/emulated/0/Python-OS-main/os.py", line 30, in <module>                                 Os.iconbitmap(Assets_dir + "/Images/icon.ico")  # Window icon                                     File "/data/data/com.termux/files/usr/lib/python3.10/tkinter/__init__.py", line 2109, in wm_iconbitmap     return self.tk.call('wm', 'iconbitmap', self._w, bitmap) _tkinter.TclError: bitmap "/storage/emulated/0/Python-OS-main/Assets/Images/icon.ico" not defined

### ISSUE THREAD

**Issue by MichnoAZ** [TheBigEye/Python-OS#8]
Runned on:Termux (Using vncserver for gui)
Python version: Python 3.10.2 (main, Jan 16 2022, 02:59:01) [Clang 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7 on linux

Device: Redmi 7a
Error:
Traceback (most recent call last):                  File "/storage/emulated/0/Python-OS-main/os.py", line 30, in <module>                                 Os.iconbitmap(Assets_dir + "/Images/icon.ico")  # Window icon                                     File "/data/data/com.termux/files/usr/lib/python3.10/tkinter/__init__.py", line 2109, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/storage/emulated/0/Python-OS-main/Assets/Images/icon.ico" not defined

**Comment by TheBigEye** [comment]
It seems that Linux doesn't support icons (.ico) like Windows does, I'll create a check for Linux systems and will use an icon (.xbm) instead.

Still, if you want to run the project still, you should delete line 30 in Os.py, that will load the default Tkinter icon so you can run it.

Thanks for the issue report  :D
